# Generated by Django 5.2.7 on 2025-10-06 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.TextField(max_length=200)),
                ('Product_image', models.ImageField(default=None, max_length=250, upload_to='Product_Entry_Image')),
                ('Product_id', models.IntegerField(default=None, max_length=20)),
                ('Product_quantity', models.IntegerField(max_length=50)),
                ('Product_inOut', models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
