# Generated by Django 5.2.7 on 2026-04-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_product_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_entry',
            name='Product_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='product_entry',
            name='Product_quantity',
            field=models.IntegerField(),
        ),
    ]
